# Generated by Django 2.2 on 2019-05-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empview',
            fields=[
                ('employees_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employees_name', models.CharField(blank=True, max_length=45, null=True)),
                ('employees_job_title', models.CharField(blank=True, max_length=45, null=True)),
                ('employees_salary', models.IntegerField(blank=True, null=True)),
                ('emp_accounts_credit', models.FloatField(blank=True, null=True)),
                ('emp_accounts_debit', models.FloatField(blank=True, null=True)),
                ('employees_status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'empview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDef',
            fields=[
                ('sales_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=45, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=45, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockSDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buity_no', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=45, null=True)),
                ('puchase_price', models.FloatField(blank=True, null=True)),
                ('retail_price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_s_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accounts_id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_name', models.CharField(blank=True, max_length=45, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('bal', models.FloatField(blank=True, null=True)),
                ('var', models.FloatField(blank=True, null=True)),
                ('bkvar', models.FloatField(blank=True, null=True)),
                ('opn_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabakLedger',
            fields=[
                ('babak_ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('debit_amount', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=90, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('rmb', models.FloatField(blank=True, null=True)),
                ('rup', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employees_id', models.AutoField(primary_key=True, serialize=False)),
                ('employees_name', models.CharField(blank=True, max_length=45, null=True)),
                ('employees_job_title', models.CharField(blank=True, max_length=45, null=True)),
                ('employees_salary', models.IntegerField(blank=True, null=True)),
                ('employees_status', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManiPro',
            fields=[
                ('mani_pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('qty', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('parts_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('qty', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(db_column='Products_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('p_p', models.FloatField(blank=True, null=True)),
                ('r_p', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('e_code', models.CharField(blank=True, max_length=45, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProVdPpPr',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=45, null=True)),
                ('p_pp', models.FloatField(blank=True, null=True)),
                ('p_rp', models.FloatField(blank=True, null=True)),
                ('saled_price', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('sal_id', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalDetails',
            fields=[
                ('sal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('net_total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salesreturn',
            fields=[
                ('salesreturn_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=45, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('net_total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(blank=True, max_length=45, null=True)),
                ('bilno', models.IntegerField(blank=True, null=True)),
                ('no_of_pro', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('stock_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(blank=True, max_length=55, null=True)),
                ('p_p', models.FloatField(blank=True, null=True)),
                ('r_p', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('stock_stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Salesreturndetail',
            fields=[
                ('salesreturndetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('ecode', models.CharField(blank=True, max_length=45, null=True)),
                ('salesreturn_salereturn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Salesreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('sales_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('dis', models.FloatField(blank=True, null=True)),
                ('ecode', models.CharField(blank=True, max_length=45, null=True)),
                ('sales_sales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('purchase_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(blank=True, max_length=55, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('p_p', models.FloatField(blank=True, null=True)),
                ('r_p', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('purchase_purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PayLed',
            fields=[
                ('pay_led_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('customers_customers', models.ForeignKey(db_column='customers_customers', on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='ExpDetails',
            fields=[
                ('exp_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('amt', models.FloatField(blank=True, null=True)),
                ('exp_exp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Exp')),
            ],
        ),
        migrations.CreateModel(
            name='EmpAccounts',
            fields=[
                ('emp_accounts_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_account_name', models.CharField(blank=True, max_length=45, null=True)),
                ('emp_accounts_credit', models.FloatField(blank=True, null=True)),
                ('emp_accounts_debit', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('employees_employees', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='DebRecvLedger',
            fields=[
                ('deb_recv_ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('debit_amount', models.FloatField(blank=True, null=True)),
                ('customers_customers', models.ForeignKey(db_column='customers_customers', on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(blank=True, max_length=55, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('amt', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('ecode', models.CharField(blank=True, max_length=45, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('booking_booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsLedger',
            fields=[
                ('accounts_ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('given_from', models.CharField(blank=True, max_length=45, null=True)),
                ('given_to', models.CharField(blank=True, max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=45, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
                ('accounts_accounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Accounts')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='customers_cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sun.Customers'),
        ),
    ]
